
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: circuit_breaker_python
    description: "A model demonstrating circuit breaker pattern with Python integration"
    columns:
      - name: todo_id
        description: "The ID of the created todo item"
        tests:
          - not_null
      - name: status
        description: "The status of the circuit breaker operation"
        tests:
          - not_null
      - name: polls_completed
        description: "Number of successful poll attempts completed"
        tests:
          - not_null
      - name: deletion_success
        description: "Whether the todo item was successfully deleted"
        tests:
          - not_null
