
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: circuit_breaker_python
    description: "A model demonstrating circuit breaker pattern with Python integration"
    columns:
      - name: todo_id
        description: "The ID of the created todo item"
        tests:
          - not_null
      - name: status
        description: "The status of the circuit breaker operation"
        tests:
          - not_null
      - name: polls_completed
        description: "Number of successful poll attempts completed"
        tests:
          - not_null
      - name: deletion_success
        description: "Whether the todo item was successfully deleted"
        tests:
          - not_null

  - name: policy_execution_model
    description: "A model that executes the complete policy workflow: create -> poll -> circuit breaker"
    columns:
      - name: execution_id
        description: "The unique identifier for the policy execution"
        tests:
          - not_null
      - name: policy_id
        description: "The unique identifier for the created policy"
        tests:
          - not_null
      - name: status
        description: "The final status of the policy execution (policy_ready, completed, error)"
        tests:
          - not_null
      - name: polls_completed
        description: "Number of policy status polling attempts completed (max 3)"
        tests:
          - not_null
      - name: circuit_breaker_initiated
        description: "Whether circuit breaker has been initiated"
        tests:
          - not_null
      - name: circuit_breaker_completed
        description: "Whether circuit breaker API call has been completed successfully"
        tests:
          - not_null
      - name: success
        description: "Whether the entire policy execution workflow was successful"
        tests:
          - not_null
      - name: completed
        description: "Whether the workflow has been completed (success or failure)"
        tests:
          - not_null

  - name: test_createpolicy_api
    description: "A test model demonstrating direct API call to createpolicy endpoint"
    columns:
      - name: api_response
        description: "The full API response from the createpolicy endpoint"
        tests:
          - not_null

  - name: policy_execution_results
    description: "A view showing policy execution results for monitoring"
    columns:
      - name: execution_id
        description: "The unique identifier for the policy execution"
      - name: policy_id
        description: "The unique identifier for the created policy"
      - name: status
        description: "The current status of the policy execution"
      - name: polls_completed
        description: "Number of polling attempts completed"
      - name: circuit_breaker_completed
        description: "Whether circuit breaker has been completed"
      - name: success
        description: "Whether the policy execution was successful"
